const config = require('../../config');

const ABBREVIATIONS = {
  'mb': 'benim hatam',
  'yb': 'senin hatandı',
  'kb': 'kusura bakma',
  'sa': 'selamün aleyküm',
  'as': 'aleyküm selam',
  'hg': 'hoş geldin',
  'ho': 'hayırlı olsun',
  'hb': 'hoş bulduk',
  'inş': 'inşallah',
  'bb': 'görüşürüz',
  'slm': 'selam',
  'nbr': 'naber',
  'eyw': 'eyvallah',
  'eyv': 'eyvallah',
  'hll': 'helal olsun',
  'hl': 'helal',
  'ns': 'mükemmel şut',
  'ds': 'çok iyi asist',
  'wp': 'güzel oynadın',
  'tb': 'tebrikler',
  'gg': 'güzel oyundu',
  'ez': 'kolaydı',
  'es': 'eline sağlık',
  'est': 'estağfurullah',
  'estf': 'estağfurullah',
  'gh': 'iyi kaleci',
  'ty': 'teşekkürler',
  'tşk': 'teşekkürler',
  'np': 'önemli değil',
  'öd': 'önemli değil',
  'hf': 'iyi eğlenceler',
  'gj': 'iyi işti',
  'nt': 'iyi denemeydi',
  'bg': 'kötü oyundu',
  'idk': 'bilmiyorum',
  'pls': 'lütfen',
  'lol': 'hahaha',
  'omg': 'aman tanrım',
  'wtf': 'bu ne ya',
  'gk': 'kaleci',
  'fw': 'forvet',
  'kg': 'kolay gelsin',
  'gp': 'geri pas',
  'op': 'orta pas',
  'dp': 'düz pas',
  'bp': 'bana pas',
  'sry': 'özür dilerim',
  'thx': 'sağol',
  '+': 'evet',
  '-': 'hayır',
  'tm': 'tamam',
  'd': '😁',
  'D': '😁'
};

const INLINE_EMOJIS = {
  ':)': '😊',
  ':d': '😁',
  ':D': '😁',
  ':(': '😢',
  ':p': '😛',
  ':P': '😛',
  ';)': '😉',
  '<3': '❤️',
  ':o': '😮',
  ':O': '😮',
  'xd': '🤣',
  'XD': '🤣',
  ':*': '😘',
  ':/': '😕',
  ':s': '😬',
  ':S': '😬',
  'o7': '🫡',
  ':3': '😺',
  ':c': '😞',
  ':C': '😞',
  ':x': '🤐',
  ':X': '🤐',
  ':b': '😋',
  ':B': '😎',
  '>:(': '😠',
  '>:)': '😈',
  ':\'(': '😭',
  'B)': '😎',
  '-_-': '😑',
  ':l': '😐',
  ':L': '😐',
  ':@': '😡',
  ':$': '😳',
  ':z': '😴',
  ':Z': '😴',
  '^_^': '😄',
  '^-^': '😊',
  'o_o': '😳',
  'O_O': '😱',
  '-.-': '😒',
  'uwu': '🥺',
  'UwU': '🥺',
  ':v': '😏',
  ':V': '🦆',
  ':>': '😏',
  ':<': '😟',
  ';p': '😜',
  ';P': '😜',
  ';d': '😜',
  ';D': '😜'
};

const TIMING = {
  BALANCE_DELAY: 400,
  TEAM_CHECK_DELAY: 300,
  GAME_START_DELAY: 500,
  MAP_CHANGE_DELAY: 400,
  ROTATION_STEP_DELAY: 300,
  PLAYER_JOIN_DELAY: 200,
  PLAYER_LEAVE_DELAY: 200,
  POST_VICTORY_DELAY: 1200,
  POST_GAME_STOP_DELAY: 300,
  TEAM_SHUFFLE_DELAY: 400,
};

const PLAYER_SIZE = {
  DEFAULT_RADIUS: 15,
  GOAL_RADIUS: 80,
  OWN_GOAL_RADIUS: 7,
};

const CELEBRATION = {
  DISC_COUNT: 12,
  DISC_START_INDEX: 5,
  ORBIT_MULTIPLIER: 1.2,
  ORBIT_SPEED: 0.1,
  DURATION_TICKS: 180,
  DISC_RADIUS: 4,
  COLORS: {
    RED: 0xE56E56,
    BLUE: 0x5689E5,
    GOLD: 0xFFD700,
  },
  TEXT_DISC_START: 17,
  TEXT_DISC_COUNT: 70,
  TEXT_DURATION_TICKS: 120,
  TEXT_PIXEL_SIZE: 6,
  TEXT_SPACING: 1,
};

const DURATIONS = {
  CAPTAIN_TIMEOUT: config.captainTimeout * 1000,
  INACTIVITY_KICK: (config.afkKickTimeout || 8) * 1000,
  ACTIVITY_CLEANUP: 30 * 60 * 1000,
  INACTIVITY_CHECK_INTERVAL: 1000,
};

const Team = {
  SPECTATORS: 0,
  RED: 1,
  BLUE: 2,
};

const GameMode = {
  IDLE: 'IDLE',
  PLAYING: 'PLAYING',
  CAPTAIN_SELECTION: 'CAPTAIN_SELECTION',
  ROTATING: 'ROTATING',
  BALANCING: 'BALANCING',
};

module.exports = {
  TIMING,
  DURATIONS,
  Team,
  GameMode,
  ABBREVIATIONS,
  INLINE_EMOJIS,
  PLAYER_SIZE,
  CELEBRATION,
};
